export const UPDATE_MYLIST_PENDING = 'UPDATE_MYLIST_PENDING';
export const UPDATE_MYLIST_SUCCESS = 'UPDATE_MYLIST_SUCCESS';
export const UPDATE_MYLIST_FAILED = 'UPDATE_MYLIST_FAILED';

export const MAP_USER_MYLIST = 'GET_USER_MYLIST';

export const GET_USER_MYLIST_PENDING = 'GET_USER_MYLIST_PENDING';
export const GET_USER_MYLIST_SUCCESS = 'GET_USER_MYLIST_SUCCESS';
export const GET_USER_MYLIST_FAILED = 'GET_USER_MYLIST_FAILED';
